export enum COMMAND {
  UNKNOWN_COMMAND = 'UNKNOWN_COMMAND',
  NO_PERMITION = 'NO_PERMITION',

  DING_START = '#ding-start',
  DONG = '#dong',

  DDR = '#ddr',
  DEAD = '#dead',
  INFO = '#info',

  CLEAR = '#clear',
  RESET = '#reset',
  DEL = '#del',
  ZW = '#ZW',
  TOKEN = '#token',
  TYPE = '#type',
  SUBSCRIBE = '#I WANT TO RECEIVE WARNING NOTIFIER!',
  UNSUBSCRIBE = '#I DO NOT WANT TO RECEIVE WARNING NOTIFIER ANY MORE!',
}

export const COMMAND_LIST = [
  COMMAND.DING_START,
  COMMAND.DONG,
  COMMAND.DDR,
  COMMAND.DEAD,
  COMMAND.INFO,
  COMMAND.CLEAR,
  COMMAND.RESET,
  COMMAND.DEL,
  COMMAND.ZW,
  COMMAND.TOKEN,
  COMMAND.TYPE,
  COMMAND.SUBSCRIBE,
  COMMAND.UNSUBSCRIBE,
];

export const PRIVATE_LIST = [
  COMMAND.CLEAR,
  COMMAND.RESET,
  COMMAND.DEL,
  COMMAND.ZW,
];
